### ISSUE TITLE
MH3SP/MHTrIDA

### ISSUE THREAD

**Issue by AldoSullivan** [sepalani/MH3SP#1]
Hello sepalani!
I received some news on the creation of a private server for mhtri.
I want to know something, you can make accessible the entire area LOC LAC (without having to create a private server, offline in short) ??
Thank you for the work you are doing!

**Comment by sepalani** [comment]
Hello and thanks for your interest in the project. To answer your question, that's not actually the case.

The goal of:
 * [MH3SP](https://github.com/sepalani/MH3SP), is to provide a bunch of tools and servers to allow people to host autonomous MH3 servers.
 * [MHTrIDA](https://github.com/sepalani/MHTrIDA), is to document the game as much as possible in order to make the reverse engineering of the game easier.

In sum, when the project will be complete people and I will be able to run MH3's Capcom servers locally (so they're "private servers"). Since we can run gamespy servers locally through [altwfc](https://github.com/polaris-/dwc_network_server_emulator), we would have all the servers the game needs to go online.

Plus, because you can host them locally on the same network, you'll be able to play without an Internet connection. Then, it's up to you to share it over the Internet by opening your router's ports or to leave them close if you don't want to play with players from the Internet.

For the moment, as said [here](https://github.com/sepalani/MH3SP/blob/master/README.md), I'm stuck at the loading bar with a value of 85%. By the way, don't expect to see something functional before at least **two or three decades**. Reversing the game takes times, especially when it is assembly language! I'm sharing all the reverse stuff I do in the MHTrIDA repository, for instance in-game functions are the ones I'm currently working on.

If you want to help, feel free to clone those repositories. But keep in mind, **I'm not a teacher! You'll have to learn by yourselves!** Here are the requirement to be able to help:
 - Be autonomous
 - Know how to reverse (engineer) a Wii game
 - Be a programmer with at least the following skills:
   - Assembly Language Programming (PPC750cl)
   - Network Programming
   - SSL/TLS Network Programming
   - Know how to git Git (optional)

In order to debug the game you'll have to use an either an emulator or a real Wii with an USB Gecko.

That's pretty much it.

Cordially,
Sepalani.

**Comment by IncognitoMan** [comment]
I know this would be completely OT but do you hang around on IRC or some other method of contact? ( kinda sad that they removed private messaging )

**Comment by RuckeySquad** [comment]
what do you mean exactly?

Date: Fri, 18 Mar 2016 08:35:48 -0700

**Comment by IncognitoMan** [comment]
a method of contact that wouldnt use the issue tickets like IRC ( freenode ) or some other method of chat service ( Skype, Discord.... whatever you want to use... ) so that it would be easier to ask a series of questions that I have regarding the project.

**Comment by sepalani** [comment]
If you want to ask something, just open a new issue with an appropriate title. Your questions might interest someone else.

**Comment by RuckeySquad** [comment]
oh, at most i have discord for contacting people.. just wondering, what exactly would you wish to talk about if i were create a chat room... this email just kinda came out of nowhere so i'm a bit cautious

Date: Fri, 18 Mar 2016 12:31:12 -0700

**Comment by sepalani** [comment]
That email comes from the github notification system. You can answer with github if you don't want to answer by mail.

**Comment by RuckeySquad** [comment]
i'm starting to feel like the notification i got was intended for the creator of the project instead of me
Date: Fri, 18 Mar 2016 13:10:33 -0700
