### ISSUE TITLE
Error 20100

### ISSUE THREAD

**Issue by KefCry** [sepalani/MH3SP#128]
Hi,

I applied the pacth to the Monster Hunter Tri ISO. 
When I launch via the patched shortcut, I get the choice of village or town. 
However, when loading the online mode, at 20%, I get error 20100.

**Comment by sepalani** [comment]
This place isn't used to look for support but report bug/issues regarding the server code/behaviour.

If you're trying to join the open-beta server, check the Discord and make sure you're following the guide properly. Otherwise, if you're using MH3SP to host the server locally, it might be a network issue on your end, see: https://github.com/sepalani/MH3SP/wiki/Troubleshooting#error-code-20100.
